---
# https://cirrus-ci.org/guide/writing-tasks/
# https://cirrus-ci.org/examples/

container:
  cpu: 1
  memory: "2G"

lint_markdown_task:
  name: "Lint Markdown"
  container:
    image: "docker.io/library/node:alpine3.16"
  install_script: "npm install -g markdownlint-cli"
  lint_script: "markdownlint *.md docs/*.md"

lint_yaml_task:
  name: "Lint YAML"
  container:
    image: "docker.io/pipelinecomponents/yamllint:0.20.6"
  script: "yamllint ."

lint_python_task:
  name: "Lint Python"
  container:
    image: "docker.io/alpine/flake8:5.0.4"
  lint_script: "flake8"

format_python_task:
  name: "Format Python"
  container:
    image: "docker.io/pipelinecomponents/black:0.14.1"
  script: "black ."

sort_python_task:
  name: "Sort Python"
  container:
    image: "docker.io/library/python:3.9-alpine"
  install_script: "pip install isort"
  script: "isort ."
...
